import json


def save(game_map, position, filename="savegame.json"):
    """
    Saves game using json dump

    Args:
        game_map ([[str...]...]): game map generated by game_generator module.
        position ([int,int]): player's position
        filename (str): optional filename
    """
    game_map.append(position)
    with open(filename, "w") as fout:
        json.dump(game_map, fout)


def load(filename="savegame.json"):
    """
    Loads game using json.load

    Args:
        filename (str): optional filename
    Returns:
        [[str...]...] - game_map, [int, int] - position
    """
    with open(filename, "r") as fin:
        game_map = json.load(fin)
        position = game_map.pop()
        return game_map, position


def load_check(mstr, game_map, position):
    if mstr.casefold() == "save".casefold():
        save(game_map, position)
